<?php

namespace PointCollectBundle\Repository;

/**
 * TypePointCollectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePointCollectRepository extends \Doctrine\ORM\EntityRepository
{

}
